# Generated by Django 6.1.1 on 2026-09-24 11:51

from django.db import migrations

def create_default_roles(apps, schema_editor):

    Role = apps.get_model("users", "Role")

    Role.objects.get_or_create(
        name="Admin",
        defaults={
            "description": "Full system administration access."
        }
    )

    Role.objects.get_or_create(
        name="Manager",
        defaults={
            "description": "Team management and reporting access."
        }
    )

    Role.objects.get_or_create(
        name="Employee",
        defaults={
            "description": "Standard employee application access."
        }
    )
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
