# Generated by Django 6.1.1 on 2026-09-24 15:02

from django.db import migrations


def create_default_permissions(apps, schema_editor):

    Permission = apps.get_model("users", "Permission")

    permissions = [
        {
            "name": "manage_users",
            "description": "Manage system users.",
        },
        {
            "name": "assign_roles",
            "description": "Assign roles to users.",
        },
        {
            "name": "view_team_reports",
            "description": "View team reports.",
        },
        {
            "name": "use_ai_assistant",
            "description": "Use the AI assistant.",
        },
        {
            "name": "upload_documents",
            "description": "Upload documents.",
        },
        {
            "name": "view_own_documents",
            "description": "View own documents.",
        },
        {
            "name": "analyze_data",
            "description": "Analyze uploaded data.",
        },
        {
            "name": "generate_reports",
            "description": "Generate reports.",
        },
    ]

    for permission in permissions:
        Permission.objects.get_or_create(
            name=permission["name"],
            defaults={
                "description": permission["description"]
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_permission_rolepermission"),
    ]

    operations = [
        migrations.RunPython(
            create_default_permissions
        ),
    ]