# Generated by Django 6.1.1 on 2026-09-24 15:06

from django.db import migrations


def assign_default_role_permissions(apps, schema_editor):

    Role = apps.get_model("users", "Role")
    Permission = apps.get_model("users", "Permission")
    RolePermission = apps.get_model("users", "RolePermission")

    permission_map = {
        "Admin": [
            "manage_users",
            "assign_roles",
            "view_team_reports",
            "use_ai_assistant",
            "upload_documents",
            "view_own_documents",
            "analyze_data",
            "generate_reports",
        ],

        "Manager": [
            "view_team_reports",
            "use_ai_assistant",
            "upload_documents",
            "view_own_documents",
            "analyze_data",
            "generate_reports",
        ],

        "Employee": [
            "use_ai_assistant",
            "upload_documents",
            "view_own_documents",
            "analyze_data",
            "generate_reports",
        ],
    }

    for role_name, permission_names in permission_map.items():

        role = Role.objects.get(
            name=role_name
        )

        for permission_name in permission_names:

            permission = Permission.objects.get(
                name=permission_name
            )

            RolePermission.objects.get_or_create(
                role=role,
                permission=permission
            )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_create_default_permissions"),
    ]

    operations = [
        migrations.RunPython(
            assign_default_role_permissions
        ),
    ]